### PR TITLE
Fix image analysis request dispatching for breakglass mode

### LINKED ISSUE #39: Image analysis requests not dispatched for BreakGlassMode validation
If the user has configured the admission controller to request analysis for images, and an image gets evaluated by the controller using "break glass mode", the request is approved by the controller but the controller never sends the analysis request to Anchore — and it should.

#### Developer notes:

- `validation.BreakGlass()` is not setting the `Mode` field on the returned `Result`, but it should set `Mode` to `BreakGlassMode`. This leads to `shouldRequestAnalysis` not being able to leverage the `result.Mode == validation.BreakGlassMode` check.
- The testing of hook validation calls should be expanded to account for more configuration possibilities, and notably, to check for analysis requests being dispatched as expected.

### PR DESCRIPTION
**Pull request by luhring**
- moves validation-related concepts (like policy selection and gate configuration) from `admission` to `validation` package
- unexports Hook's struct fields (to make this decidedly an _object_ and not a _data structure_, since no code needed access to this data once a Hook was constructed)
- modifies the `ImageBackend` abstraction such that user credentials can be supplied for each individual method call, rather than needing to be stored in the underlying implementation upfront (which didn't map to the business expectation that the user on behalf of which requests to Anchore are made can be selected dynamically)
- moves validation method **selection** from the `admission` package to the `validation` package, which then allows specific validation implementations to be unexported
- adds test cases to verify analysis requests are (or aren't) be dispatched to Anchore as expected for the given scenario
- fixes #39 (by adjusting breakglass implementation to include its validation mode in its result)

### CODE REVIEW

File: cmd/kubernetes-admission-controller/validation/validator.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+		return func() Result {
+			return analysis(imageBackend, user, imageReference)
+		}, nil
+
+	case BreakGlassMode:
+		return breakGlass, nil
+
+	default:
+		message := fmt.Sprintf("got unexpected mode value %q for matching selector. failing on error.", mode)
+		klog.Error(message)
```
Comment (wagoodman) [inline cmd/kubernetes-admission-controller/validation/validator.go:35]: nit: logging the error at the right level seems to be up to the caller (the message specifically calls out "failing on error"). Something like:
```go
if err != nil {
   klog.Error(err)
   return validation.Result{...}
}
```
up around the caller (https://github.com/anchore/kubernetes-admission-controller/pull/40/files#diff-6fe3f359b366ce5d6a1a2cd59a4ae02c4f35cefa7c2fcc250e8a90a768bbf60bR178)

File: cmd/kubernetes-admission-controller/anchore/anchore_api_image_backend.go [hunk 2]
```diff
@@ -13,35 +13,31 @@ import (
 	"k8s.io/klog"
 )
 
-type anchoreAPIImageBackend struct {
+type APIImageBackend struct {
```
Comment (wagoodman) [inline cmd/kubernetes-admission-controller/anchore/anchore_api_image_backend.go:16]: was this type exported intentionally?

Comment (wagoodman) [reply cmd/kubernetes-admission-controller/anchore/anchore_api_image_backend.go:16]: resolved from an offline conversation

**Review by wagoodman — APPROVED** [review]

File: cmd/kubernetes-admission-controller/validation/validator.go (hunk 1 above)
Comment (luhring) [reply cmd/kubernetes-admission-controller/validation/validator.go]: @wagoodman Good catch! This is inconsistent; and, the `validation` package shouldn't report messages like "failing on error", because ultimately deciding failure is the `admission` package's responsibility. This has been adjusted to be consistent with other error handling in the project.

Let me know what you think: https://github.com/anchore/kubernetes-admission-controller/pull/40/commits/49afc05b20aca5faecc2b4ea5798f641db05efa0

**Review by zhill — APPROVED** [review]
lgtm
